### ISSUE TITLE
one suggestion: Add ViaFabricPlus mode

### ISSUE THREAD

**Issue by Psyko38** [Fabulously-Optimized/wiki#93]
ViaFabricPlus is a mode for connecting to all types of minecraft servers like verion 1.0 while remaining on the actuall minecraft version.

**Comment by Madis0** [comment]
Wrong repo for suggestions. I had considered ViaVersion in general a long time ago, but it was deemed a bit too dangerous to include, some anticheats don't like it and some rules don't allow it. See https://github.com/Fabulously-Optimized/fabulously-optimized/issues/15

**Comment by Kichura** [comment]
Since ViaFabricPlus is essentially similar to multiconnect with the same hit-or-miss anti-cheat scenario, this suggestion will be rejected aswell; But there is a wiki that let's you obtain viafabric on your client in case it's urgent for you at all. *(this includes the ability to play 1.17.1 on OpenGL 2.1 - 3.1 machines)*
